#%RAML 1.0 NamedExample
value:
  projectId: "12"
  module: "module"
  title: "Some Title"
  description: "Description"
  dateTerminated: "31-12-2021"
  owner: "U31"
  assigner: "U13"
  taskStatus: "New"
  type: "type"
  priority: "High"