#%RAML 1.0 NamedExample
value:
  name: "User Full Name"
  contact: "1234567890"
  dob: "31-12-2021"
  email: "user@domain"
  username: "username123"
  password: "password123"
  roleId: "Master"
  projectId: "12"