#%RAML 1.0 DataType
description: Message body for POST /task
properties:
  projectId: string
  module: string
  title: string
  description: string
  dateTerminated: string
  owner: string
  assigner: string
  taskStatus: string
  type: string
  priority: string