#%RAML 1.0 DataType
description: Data type for Summary
type: object
properties:
  totalCount: string
  activeCount: string
  completedCount: string
  moduleData:
    type: array
    items:
        type: object
        properties:
          moduleName: string
          count: string