#%RAML 1.0 DataType
description: Datatype for Task Assignment Summary
properties:
  new: string
  in-progress: string
  self-committed: string
  self-deleted: string
  committed: string
  deleted: string