#%RAML 1.0 DataType
description: Data Type for View Task_Master
properties:
  taskId: string
  taskAssigner: string
  description: string
  dateCreated: string
  dateTerminated: string
  module: string
  order: string
  taskOwner: string
  priority: string
  title: string
  type: string
  taskStatus: string
  assignerName: string
  ownerName: string
  projectId: string
  project: string