#%RAML 1.0 Library
usage: This is library for Generic Responses

types:
  generic_msg_type: !include Model/generic_message.raml
  
uses:
  record_add_success: !include Sample Responses/record_add_success.raml
  record_add_failure: !include Sample Responses/record_add_failure.raml
  record_update_success: !include Sample Responses/record_update_success.raml
  record_update_failure: !include Sample Responses/record_update_failure.raml
  record_delete_success: !include Sample Responses/record_delete_success.raml
  record_delete_failure: !include Sample Responses/record_delete_failure.raml