#%RAML 1.0 NamedExample
value:

  -
    projectId: "12"
    projectName: "Project 1"
  -
    projectId: "13"
    projectName: "Project 2"
  -
    projectId: "14"
    projectName: "Project 3"
  -
    projectId: "15"
    projectName: "Project 4"

  