#%RAML 1.0 NamedExample
value:

  -
    roleName: "Administrator"
    securityLevel: "1"
  -
    roleName: "Associate Administrator"
    securityLevel: "2"
  -
    roleName: "Senior Software Engineer"
    securityLevel: "4"
  -
    roleName: "Software Engineer"
    securityLevel: "5"
  