#%RAML 1.0 NamedExample
value:

  -
    sprintId: "1"
    sprintName: "Sprint 2022-01"
    startDate: "01-01-2022"
    endDate: "01-02-2022"
  -
    sprintId: "2"
    sprintName: "Sprint 2022-02"
    startDate: "01-02-2022"
    endDate: "01-03-2022"
  -
    sprintId: "3"
    sprintName: "Sprint 2022-03"
    startDate: "01-03-2022"
    endDate: "01-04-2022"
  -
    sprintId: "4"
    sprintName: "Sprint 2022-04"
    startDate: "01-04-2022"
    endDate: "01-05-2022"
  