#%RAML 1.0 NamedExample
value:

  -
    ownerName: "User 1"
    count: "14"
  -
    ownerName: "User 2"
    count: "21"

  -
    ownerName: "User 3"
    count: "18"
  
  -
    ownerName: "User 4"
    count: "17"
