#%RAML 1.0 NamedExample
value:

  -
    taskId: "123"
    title: "Task 1"
    module: "module 1"
  -
    taskId: "124"
    title: "Task 2"
    module: "module 1"
  -
    taskId: "125"
    title: "Task 1"
    module: "module 2"
