#%RAML 1.0 NamedExample
value:

  -
    userId: "U12"
    userName: "User 1"
    roleId: "1"
    roleName: "Administrator"
  -
    userId: "U23"
    userName: "User 2"
    roleId: "5"
    roleName: "Tech Lead"
  -
    userId: "U34"
    userName: "User 3"
    roleId: "7"
    roleName: "Software Engineer"
  